### ISSUE TITLE
Handle Registration gives 'missing host link to' error

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#129]
on branch `handle` commit ea3ced93ceec3c6fff42439da563135679c80038

```
$ HDL_HOME=/Users/mark/Documents/workspace/_no_backup_/deploying_hydra/handle-docker/hs/hsj-8.1.1 bundle exec rake epigaea:handle:register['c247ds08x']
rake aborted!
ArgumentError: Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true
/Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/actionpack-5.0.4/lib/action_dispatch/http/url.rb:62:in `full_url_for'
/Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/actionpack-5.0.4/lib/action_dispatch/http/url.rb:52:in `url_for'
/Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:303:in `block in <class:RouteSet>'
/Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:719:in `url_for'
/Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:236:in `call'
/Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:177:in `call'
/Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/actionpack-5.0.4/lib/action_dispatch/routing/route_set.rb:295:in `block (2 levels) in define_url_helper'
/Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/actionpack-5.0.4/lib/action_dispatch/routing/polymorphic_routes.rb:218:in `polymorphic_method'
/Users/mark/Documents/workspace/_no_backup_/RubyMine_Projects/epigaea/lib/tufts/handle_registrar.rb:125:in `url_for'
/Users/mark/Documents/workspace/_no_backup_/RubyMine_Projects/epigaea/lib/tufts/handle_registrar.rb:100:in `update_record'
/Users/mark/Documents/workspace/_no_backup_/RubyMine_Projects/epigaea/lib/tufts/handle_registrar.rb:54:in `register!'
/Users/mark/Documents/workspace/_no_backup_/RubyMine_Projects/epigaea/lib/tufts/handle_dispatcher.rb:77:in `assign_for'
/Users/mark/Documents/workspace/_no_backup_/RubyMine_Projects/epigaea/lib/tufts/handle_dispatcher.rb:87:in `assign_for!'
/Users/mark/Documents/workspace/_no_backup_/RubyMine_Projects/epigaea/lib/tufts/handle_dispatcher.rb:57:in `assign_for!'
/Users/mark/Documents/workspace/_no_backup_/RubyMine_Projects/epigaea/lib/tasks/handle.rake:15:in `block (3 levels) in <top (required)>'
/Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/mark/.rvm/gems/ruby-2.3.4@mira/bin/ruby_executable_hooks:15:in `eval'
/Users/mark/.rvm/gems/ruby-2.3.4@mira/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => epigaea:handle:register
(See full trace by running task with --trace)
```

**Comment by no-reply** [comment]
This is fixed in a force push to #125 (972010e2cbd9)
