### ISSUE TITLE
Give better handle errors

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#130]
**ISSUE**
The application appears to be throwing away the error response from the handle server rather than capturing it in the log or displaying in on the console (for the rake task)

**CURREN BEHAVIOR**
*on the command line*
```
HDL_HOME=/Users/mark/Documents/workspace/_no_backup_/deploying_hydra/handle-docker/hs/hsj-8.1.1 bundle exec rake epigaea:handle:register['c247ds08x']
rake aborted!
Handle::HandleError: Handle::HandleError
/Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/handle-system-0.1.1/lib/handle/command/persistence.rb:31:in `save'
/Users/mark/Documents/workspace/_no_backup_/RubyMine_Projects/epigaea/lib/tufts/handle_registrar.rb:55:in `register!'
/Users/mark/Documents/workspace/_no_backup_/RubyMine_Projects/epigaea/lib/tufts/handle_dispatcher.rb:77:in `assign_for'
/Users/mark/Documents/workspace/_no_backup_/RubyMine_Projects/epigaea/lib/tufts/handle_dispatcher.rb:87:in `assign_for!'
/Users/mark/Documents/workspace/_no_backup_/RubyMine_Projects/epigaea/lib/tufts/handle_dispatcher.rb:57:in `assign_for!'
/Users/mark/Documents/workspace/_no_backup_/RubyMine_Projects/epigaea/lib/tasks/handle.rake:15:in `block (3 levels) in <top (required)>'
/Users/mark/.rvm/gems/ruby-2.3.4@mira/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/Users/mark/.rvm/gems/ruby-2.3.4@mira/bin/ruby_executable_hooks:15:in `eval'
/Users/mark/.rvm/gems/ruby-2.3.4@mira/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => epigaea:handle:register
(See full trace by running task with --trace)
```

*in the log*
```
A, [2017-07-27T13:22:04.430767 #46751]   ANY -- Unable to register handle 1234.DEV/C247DS08X for c247ds08x
Handle::HandleError: c247ds08x
```

**ACTUAL ERROR**
I think this is being swallowed by the `handle-system`, but gosh it would be helpful to get some of this in the log instead of having to run a debugger.
```
sending HDL-UDP request (version=2.10; oc=1; rc=0; snId=0 crt caCrt noAuth expires:Fri Jul 28 02:08:33 CDT 2017 0.0/0.0 [ ] [ ]) to 174.129.95.75:2641
  sending HDL-UDP request (version=2.10; oc=1; rc=0; snId=0 caCrt noAuth expires:Fri Jul 28 02:08:33 CDT 2017 1234.DEV/C247DS08X [ ] [ ]) to 174.129.95.75:2641
  sending HDL-UDP request (version=2.10; oc=1; rc=0; snId=0 crt caCrt noAuth expires:Fri Jul 28 02:08:33 CDT 2017 0.0/0.0 [ ] [ ]) to 174.129.95.75:2641
  sending HDL-UDP request (version=2.10; oc=1; rc=0; snId=0 caCrt noAuth expires:Fri Jul 28 02:08:33 CDT 2017 1234.DEV/C247DS08X [ ] [ ]) to 174.129.95.75:2641
  sending HDL-UDP request (version=2.10; oc=1; rc=0; snId=0 crt caCrt noAuth expires:Fri Jul 28 02:08:33 CDT 2017 0.0/0.0 [ ] [ ]) to 174.129.95.75:2641
  sending HDL-UDP request (version=2.10; oc=1; rc=0; snId=0 caCrt noAuth expires:Fri Jul 28 02:08:33 CDT 2017 1234.DEV/C247DS08X [ ] [ ]) to 174.129.95.75:2641
  sending HDL-TCP request (version=2.10; oc=1; rc=0; snId=0 crt caCrt noAuth expires:Fri Jul 28 02:08:33 CDT 2017 0.0/0.0 [ ] [ ]) to 174.129.95.75:2641
  sending HDL-HTTP request (version=2.10; oc=1; rc=0; snId=0 crt caCrt noAuth expires:Fri Jul 28 02:08:33 CDT 2017 0.0/0.0 [ ] [ ]) to 174.129.95.75:8000
Error refreshing root info: HandleException (CANNOT_CONNECT_TO_SERVER) 174.129.95.75: java.net.ConnectException: Connection refused
HandleException (CANNOT_CONNECT_TO_SERVER) 174.129.95.75: java.net.ConnectException: Connection refused
	at net.handle.hdllib.HandleResolver.sendHttpOrHttpsRequest(HandleResolver.java:2989)
	at net.handle.hdllib.HandleResolver.sendHttpRequest(HandleResolver.java:2901)
	at net.handle.hdllib.HandleResolver.sendRequestToInterface(HandleResolver.java:2293)
	at net.handle.hdllib.HandleResolver.sendRequestToServerByProtocol(HandleResolver.java:1950)
	at net.handle.hdllib.HandleResolver.sendRequestToServerByProtocol(HandleResolver.java:1810)
	at net.handle.hdllib.HandleResolver.sendRequestToServerInSiteByProtocol(HandleResolver.java:1641)
	at net.handle.hdllib.HandleResolver.sendRequestToSite(HandleResolver.java:1619)
	at net.handle.hdllib.HappyEyeballsResolver.sendRequestToSiteViaProtocol(HappyEyeballsResolver.java:211)
	at net.handle.hdllib.HappyEyeballsResolver.sendRequestToSites(HappyEyeballsResolver.java:178)
	at net.handle.hdllib.HappyEyeballsResolver.sendRequestAndSetResponseOrPublicException(HappyEyeballsResolver.java:153)
	at net.handle.hdllib.HappyEyeballsResolver.run(HappyEyeballsResolver.java:93)
	at net.handle.hdllib.HandleResolver.sendRequestToService(HandleResolver.java:1193)
	at net.handle.hdllib.HandleResolver.processRequest(HandleResolver.java:719)
	at net.handle.hdllib.HandleResolver.processRequest(HandleResolver.java:736)
	at net.handle.hdllib.Configuration.resolveHandleCertified(Configuration.java:267)
	at net.handle.hdllib.Configuration.resolveVerifyUpdateAndPersistBootstrapHandles(Configuration.java:186)
	at net.handle.hdllib.Configuration.refreshRootInfoFromNet(Configuration.java:178)
	at net.handle.hdllib.Configuration.access$000(Configuration.java:29)
	at net.handle.hdllib.Configuration$2.run(Configuration.java:308)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:111)
	at net.handle.hdllib.HandleResolver.sendHttpOrHttpsRequest(HandleResolver.java:2982)
	... 18 more
  sending HDL-TCP request (version=2.10; oc=1; rc=0; snId=0 caCrt noAuth expires:Fri Jul 28 02:08:33 CDT 2017 1234.DEV/C247DS08X [ ] [ ]) to 174.129.95.75:2641
  sending HDL-HTTP request (version=2.10; oc=1; rc=0; snId=0 caCrt noAuth expires:Fri Jul 28 02:08:33 CDT 2017 1234.DEV/C247DS08X [ ] [ ]) to 174.129.95.75:8000

Error: HandleException (CANNOT_CONNECT_TO_SERVER) 174.129.95.75: java.net.ConnectException: Connection refused
HandleException (CANNOT_CONNECT_TO_SERVER) 174.129.95.75: java.net.ConnectException: Connection refused
	at net.handle.hdllib.HandleResolver.sendHttpOrHttpsRequest(HandleResolver.java:2989)
	at net.handle.hdllib.HandleResolver.sendHttpRequest(HandleResolver.java:2901)
	at net.handle.hdllib.HandleResolver.sendRequestToInterface(HandleResolver.java:2293)
	at net.handle.hdllib.HandleResolver.sendRequestToServerByProtocol(HandleResolver.java:1950)
	at net.handle.hdllib.HandleResolver.sendRequestToServerByProtocol(HandleResolver.java:1810)
	at net.handle.hdllib.HandleResolver.sendRequestToServerInSiteByProtocol(HandleResolver.java:1641)
	at net.handle.hdllib.HandleResolver.sendRequestToSite(HandleResolver.java:1619)
	at net.handle.hdllib.HappyEyeballsResolver.sendRequestToSiteViaProtocol(HappyEyeballsResolver.java:211)
	at net.handle.hdllib.HappyEyeballsResolver.sendRequestToSites(HappyEyeballsResolver.java:178)
	at net.handle.hdllib.HappyEyeballsResolver.sendRequestAndSetResponseOrPublicException(HappyEyeballsResolver.java:153)
	at net.handle.hdllib.HappyEyeballsResolver.run(HappyEyeballsResolver.java:93)
	at net.handle.hdllib.HandleResolver.sendRequestToService(HandleResolver.java:1193)
	at net.handle.hdllib.HandleResolver.processRequest(HandleResolver.java:719)
	at net.handle.hdllib.HandleResolver.processRequest(HandleResolver.java:736)
	at net.handle.apps.simple.HDLTrace.<init>(HDLTrace.java:60)
	at net.handle.apps.simple.HDLTrace.main(HDLTrace.java:85)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:111)
	at net.handle.hdllib.HandleResolver.sendHttpOrHttpsRequest(HandleResolver.java:2982)
	... 15 more
nil
```

**Comment by mark-dce** [comment]
i.e. it's way more helpful to know:
```
(CANNOT_CONNECT_TO_SERVER) 174.129.95.75: java.net.ConnectException: Connection refused
```

than
```
Unable to register handle 1234.DEV/C247DS08X for c247ds08x
Handle::HandleError: c247ds08x
```

**Comment by no-reply** [comment]
I wonder why this isn't working. https://github.com/curationexperts/epigaea/pull/125/files#diff-7de41b13ecce2d6db65b74620e850bf7R59

**Comment by mark-dce** [comment]
Out of scope for this project to make enhancements to handle-system
