### ISSUE TITLE
Intermittent Test Failure: Changeset Comparison

### ISSUE THREAD

**Issue by no-reply** [curationexperts/epigaea#165]
Changeset comparisons in the specs fail occasionally. Ideally, we could implement `#==` on ChangeSet to resolve this issue.

**Comment by mark-dce** [comment]
I'm guessing this is the error associated with the issue referenced above (If not let's write up a second ticket for this)

```
  1) Tufts::Draft#load with saved changes retains the changes
     Failure/Error:
       expect { draft.load }
         .not_to change { draft.changeset.changes }
     
       expected `draft.changeset.changes` not to have changed, but did change from {#<RDF::URI:0x466ce1c URI:http://purl.org/dc/terms/title>=>#<RDF::Graph:0x7d1435c(default)>, #<RDF::URI:0x530d6a8 URI:http://purl.org/dc/terms/subject>=>#<RDF::Graph:0x88ed408(default)>} to {#<RDF::URI:0x466ce1c URI:http://purl.org/dc/terms/title>=>#<RDF::Graph:0xc4de354(default)>, #<RDF::URI:0x530d6a8 URI:http://purl.org/dc/terms/subject>=>#<RDF::Graph:0xc4d05b0(default)>}
     # ./spec/lib/tufts/draft_spec.rb:148:in `block (4 levels) in <top (required)>'
```

**Comment by mark-dce** [comment]
@no-reply This seems to be happening to me at least a handful of times each day.  If it's happening that often to other folks, it's probably time to refactor the test.

**Comment by mark-dce** [comment]
occurs on 
commit: 4f1c15aafecba53e8dbdf8f5e097642a0958cf2a
seed: 13816

**Comment by mark-dce** [comment]
Damn - the failures aren't even consistent on a give seed

```
MARKs-MacBook-Pro-2:epigaea mark$ bundle exec rake spec SPEC=spec/lib/tufts/draft_spec.rb:148 SPEC_OPTS='--seed 18727'
/Users/mark/.rvm/rubies/ruby-2.3.4/bin/ruby -I/Users/mark/.rvm/gems/ruby-2.3.4@epigaea/gems/rspec-core-3.6.0/lib:/Users/mark/.rvm/gems/ruby-2.3.4@epigaea/gems/rspec-support-3.6.0/lib /Users/mark/.rvm/gems/ruby-2.3.4@epigaea/gems/rspec-core-3.6.0/exe/rspec spec/lib/tufts/draft_spec.rb:148
Run options: include {:locations=>{"./spec/lib/tufts/draft_spec.rb"=>[148]}}

Randomized with seed 18727
F

Failures:

  1) Tufts::Draft#load with saved changes retains the changes
     Failure/Error:
       expect { draft.load }
         .not_to change { draft.changeset.changes }
     
       expected `draft.changeset.changes` not to have changed, but did change from {#<RDF::URI:0x3ff12a3edcfc URI:http://purl.org/dc/terms/title>=>#<RDF::Graph:0x3ff12b1a7f28(default)>...DF::URI:0x3ff1300bf340 URI:http://purl.org/dc/terms/subject>=>#<RDF::Graph:0x3ff12b197efc(default)>} to {#<RDF::URI:0x3ff12a3edcfc URI:http://purl.org/dc/terms/title>=>#<RDF::Graph:0x3ff12f61523c(default)>...DF::URI:0x3ff1300bf340 URI:http://purl.org/dc/terms/subject>=>#<RDF::Graph:0x3ff12e5dc8fc(default)>}
     # ./spec/lib/tufts/draft_spec.rb:148:in `block (4 levels) in <top (required)>'

Finished in 1.58 seconds (files took 8.79 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/lib/tufts/draft_spec.rb:147 # Tufts::Draft#load with saved changes retains the changes

Randomized with seed 18727

/Users/mark/.rvm/rubies/ruby-2.3.4/bin/ruby -I/Users/mark/.rvm/gems/ruby-2.3.4@epigaea/gems/rspec-core-3.6.0/lib:/Users/mark/.rvm/gems/ruby-2.3.4@epigaea/gems/rspec-support-3.6.0/lib /Users/mark/.rvm/gems/ruby-2.3.4@epigaea/gems/rspec-core-3.6.0/exe/rspec spec/lib/tufts/draft_spec.rb:148 failed
MARKs-MacBook-Pro-2:epigaea mark$ bundle exec rake spec SPEC=spec/lib/tufts/draft_spec.rb:148 SPEC_OPTS='--seed 18727'
/Users/mark/.rvm/rubies/ruby-2.3.4/bin/ruby -I/Users/mark/.rvm/gems/ruby-2.3.4@epigaea/gems/rspec-core-3.6.0/lib:/Users/mark/.rvm/gems/ruby-2.3.4@epigaea/gems/rspec-support-3.6.0/lib /Users/mark/.rvm/gems/ruby-2.3.4@epigaea/gems/rspec-core-3.6.0/exe/rspec spec/lib/tufts/draft_spec.rb:148
Run options: include {:locations=>{"./spec/lib/tufts/draft_spec.rb"=>[148]}}

Randomized with seed 18727
.

Finished in 1.45 seconds (files took 8.36 seconds to load)
1 example, 0 failures

Randomized with seed 18727
```

**Comment by mark-dce** [comment]
On further investigation, I'm not sure that implementing #== helps.  `draft.changset.changes` is a Hash, which has a valid #== method.  It looks to me like the values in the hashes are literally different, so you would need to inspect the actual graph members, not the change sets.

```
[144, 153] in /Users/mark/Documents/workspace/_no_backup_/RubyMine_Projects/epigaea/spec/lib/tufts/draft_spec.rb
   144: 
   145:       before { draft.save }
   146: 
   147:       it 'retains the changes' do
   148:         byebug
=> 149:         expect { draft.load }
   150:           .not_to change { draft.changeset.changes }
   151:       end
   152: 
   153:       it 'reloads saved changes' do
(byebug) draft.changeset.changes.class
Hash
(byebug) old = draft.changeset.changes
{#<RDF::URI:0x3ffc69c9ba58 URI:http://purl.org/dc/terms/title>=>#<RDF::Graph:0x3ffc657f10b0(default)>, #<RDF::URI:0x3ffc69db9d40 URI:http://purl.org/dc/terms/subject>=>#<RDF::Graph:0x3ffc657dd808(default)>}
(byebug) draft.load
#<Tufts::Draft:0x007ff8cb495248 @changeset=#<ActiveFedora::ChangeSet:0x007ff8d5467848 @object=#<FakeWork id: nil, title: ["moominmama", "snork", "moomin"], subject: ["too-ticky"], relation: [], single_value: nil>, @graph=#<FakeWork::GeneratedResourceSchema:0x3ffc6aa9d5fc(#<FakeWork::GeneratedResourceSchema:0x007ff8d553abf8>)>, @changed_attributes=["title", "subject"], @changes={#<RDF::URI:0x3ffc69c9ba58 URI:http://purl.org/dc/terms/title>=>#<RDF::Graph:0x3ffc6aa33260(default)>, #<RDF::URI:0x3ffc69db9d40 URI:http://purl.org/dc/terms/subject>=>#<RDF::Graph:0x3ffc68aec960(default)>}>, @id="2db20d26-db5b-4af7-97bb-cf2246e56eba", @model=#<FakeWork id: nil, title: ["moominmama", "snork", "moomin"], subject: ["too-ticky"], relation: [], single_value: nil>, @serializer=#<Tufts::ChangesetSerializer:0x007ff8cb457510>, @apply_strategy=#<Tufts::ChangesetOverwriteStrategy:0x007ff8cafe9c80 @changeset=#<ActiveFedora::ChangeSet:0x007ff8cb4952c0 @object=#<FakeWork id: nil, title: ["moominmama", "moomin", "snork"], subject: ["too-ticky"], relation: [], single_value: nil>, @graph=#<FakeWork::GeneratedResourceSchema:0x3ffc65a6bf5c(#<FakeWork::GeneratedResourceSchema:0x007ff8cb4d7eb8>)>, @changed_attributes=["title", "subject"], @changes={#<RDF::URI:0x3ffc69c9ba58 URI:http://purl.org/dc/terms/title>=>#<RDF::Graph:0x3ffc657f10b0(default)>, #<RDF::URI:0x3ffc69db9d40 URI:http://purl.org/dc/terms/subject>=>#<RDF::Graph:0x3ffc657dd808(default)>}>, @model=#<FakeWork id: nil, title: ["moominmama", "snork", "moomin"], subject: ["too-ticky"], relation: [], single_value: nil>>>
(byebug) new = draft.changeset.changes
{#<RDF::URI:0x3ffc69c9ba58 URI:http://purl.org/dc/terms/title>=>#<RDF::Graph:0x3ffc6aa33260(default)>, #<RDF::URI:0x3ffc69db9d40 URI:http://purl.org/dc/terms/subject>=>#<RDF::Graph:0x3ffc68aec960(default)>}
(byebug) old == new
false
(byebug) old.keys
[#<RDF::URI:0x3ffc69c9ba58 URI:http://purl.org/dc/terms/title>, #<RDF::URI:0x3ffc69db9d40 URI:http://purl.org/dc/terms/subject>]
(byebug) new.keys
[#<RDF::URI:0x3ffc69c9ba58 URI:http://purl.org/dc/terms/title>, #<RDF::URI:0x3ffc69db9d40 URI:http://purl.org/dc/terms/subject>]
(byebug) old.values
[#<RDF::Graph:0x3ffc657f10b0(default)>, #<RDF::Graph:0x3ffc657dd808(default)>]
(byebug) new.values
[#<RDF::Graph:0x3ffc6aa33260(default)>, #<RDF::Graph:0x3ffc68aec960(default)>]
```

**Comment by mark-dce** [comment]
So, it's looking to me like the Graph IDs and Statement IDs can change even through the predicates and objects in the statements are consistent.  Unfortunately, it's a little bit beyond me to figure out an elegant way to inspect the change sets this deeply.
