### ISSUE TITLE
NoMethodError in Contribute#new

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#187]
**ISSUE**
When I try to contribute a new work (from /contribute) I get the error below.

**Environment**
Local development environment 
running mater: f1cf90851baa1ff4fa3d53982bd65c73f3729344

**Steps to Reproduce**
1. Visit http://localhost:3000/contribute
1. Choose "Faculty Scholarship"
2. Click the "Begin" button

```
NoMethodError in Contribute#new

undefined method `add_field' for #<#<Class:0x007f9c9cb5a640>:0x007f9cb1d05c28>

Extracted source (around line #54):
52     content_tag :div, class: 'controls'  do
53      field = text_field_tag 'contribution[other_authors][]', author, class: 'input-large'
54      button = author.nil? ? add_field(:other_authors) : subtract_field(:other_authors)
55      field + button + authors_are_optional
56    end
57  end

Trace of template inclusion: app/views/contribute/new.html.erb

Rails.root: /Users/mark/Documents/workspace/_no_backup_/RubyMine_Projects/epigaea

Application Trace | Framework Trace | Full Trace
app/helpers/contribute_helper.rb:54:in `block in html_snippet_for_one_author'
app/helpers/contribute_helper.rb:52:in `html_snippet_for_one_author'
app/helpers/contribute_helper.rb:38:in `block in blank_author_field'
app/helpers/contribute_helper.rb:37:in `blank_author_field'
app/helpers/contribute_helper.rb:32:in `other_authors_fields'
app/views/contribute/deposit_view/_faculty_scholarship.html.erb:9:in `_app_views_contribute_deposit_view__faculty_scholarship_html_erb__2634467783553383207_70155539217920'
app/views/contribute/new.html.erb:17:in `block in _app_views_contribute_new_html_erb___1631230558380030513_70155487428360'
app/views/contribute/new.html.erb:5:in `_app_views_contribute_new_html_erb___1631230558380030513_70155487428360'
```

**Comment by mark-dce** [comment]
Duplicate of #218
