### ISSUE TITLE
Intermittent CI Error -  PermissionTemplate error

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#235]
Seed:  22065
Commit: 51ab305484ebd0f532143d1622d29093c7a4c93b

```
  1) deposit and publication a logged in user non-admin user deposits, admin publishes
     Failure/Error: Hyrax::PermissionTemplate.create(admin_set_id: AdminSet::DEFAULT_ID)
     
     ActiveRecord::RecordNotUnique:
       Mysql2::Error: Duplicate entry 'admin_set/default' for key 'index_permission_templates_on_admin_set_id': INSERT INTO `permission_templates` (`admin_set_id`, `created_at`, `updated_at`) VALUES ('admin_set/default', '2017-09-13 21:22:39', '2017-09-13 21:22:39')
     # ./lib/tufts/workflow_setup.rb:8:in `set_default_workflow'
     # ./spec/features/publication_workflow_spec.rb:15:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Mysql2::Error:
     #   Duplicate entry 'admin_set/default' for key 'index_permission_templates_on_admin_set_id'
     #   ./lib/tufts/workflow_setup.rb:8:in `set_default_workflow'
```

**Comment by bess** [comment]
I believe this is fixed in PR #243
