### ISSUE TITLE
Intermittent Failure: Hyrax::XmlImportsController GET #show renders the batch

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#337]
commit: cd2f2ea1cb52e6a05638d5d57b4f3b3ae9ddfacd
seed: 14135

Note: CI ran successfully for the PR associated with this Merge.

```
  1) Hyrax::XmlImportsController GET #show renders the batch
     Failure/Error: expect(assigns(:import).batch_presenter.object).to eq import.batch
     
       expected: #<Batch id: 1, batchable_type: "XmlImport", batchable_id: 1, user_id: 1, ids: ["abc", "123"], created_at: "2017-09-29 20:15:08", updated_at: "2017-09-29 20:15:08">
            got: nil
     
       (compared using ==)
     # ./spec/controllers/hyrax/xml_imports_controller_spec.rb:59:in `block (3 levels) in <top (required)>'
```

**Comment by mark-dce** [comment]
We suspect this was due to response delays in Capybara tests which have been resolved by increasing the CI server size.

**Comment by mark-dce** [comment]
Reopening this ticket in case we want to look at it again more deeply.  Feel free to close it if we think it's strictly a Travis CI performance issue.

Commit: a174f16e85be5299a276757ec9b89e273d5487b5  
Seed: 56872

```
Failures:
  1) Hyrax::XmlImportsController GET #show renders the batch
     
Failure/Error: expect(assigns(:import).batch_presenter.object).to eq import.batch
     
     
  expected: #<Batch id: 1, batchable_type: "XmlImport", batchable_id: 1, user_id: 1, ids: ["abc", "123"], created_at: "2017-12-12 19:33:44", updated_at: "2017-12-12 19:33:44">
     
       got: nil
     
     
  (compared using ==)
     
# ./spec/controllers/hyrax/xml_imports_controller_spec.rb:58:in `block (3 levels) in <top (required)>'
Finished in 13 minutes 1 second (files took 27.26 seconds to load)
1404 examples, 1 failure, 11 pending
Failed examples:
rspec ./spec/controllers/hyrax/xml_imports_controller_spec.rb:55
 
# Hyrax::XmlImportsController GET #show renders the batch
Randomized with seed 56872
```

**Comment by mark-dce** [comment]
See #752
