### ISSUE TITLE
Intermittent Failure: Hyrax::XmlImportsController PATCH #update when files do not match metadata enqueues jobs only for matching files

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#454]
Commit: 5a749c50bb65f361fc59680e4792b251801ce442
Seed: 1908

```
  1) Hyrax::XmlImportsController PATCH #update when files do not match metadata enqueues jobs only for matching files
     Failure/Error: batch.ids << id
     
     NoMethodError:
       undefined method `ids' for nil:NilClass
     # ./app/models/xml_import.rb:117:in `block in mint_ids'
     # ./app/models/xml_import.rb:108:in `each'
     # ./app/models/xml_import.rb:108:in `mint_ids'
     # ./app/controllers/hyrax/xml_imports_controller.rb:41:in `update'
     # ./spec/controllers/hyrax/xml_imports_controller_spec.rb:98:in `block (5 levels) in <top (required)>'
     # ./spec/controllers/hyrax/xml_imports_controller_spec.rb:98:in `block (4 levels) in <top (required)>'
Finished in 7 minutes 21 seconds (files took 23.99 seconds to load)
1363 examples, 1 failure, 31 pending
Failed examples:
rspec ./spec/controllers/hyrax/xml_imports_controller_spec.rb:97 # Hyrax::XmlImportsController PATCH #update when files do not match metadata enqueues jobs only for matching files
Randomized with seed 1908
```

**Comment by mark-dce** [comment]
Initially I thought this was the same as #338 / #373 at first, but looking more closely it appears to be a different issue.  But possibly related to those?

**Comment by mark-dce** [comment]
We believe this has been resolved by increasing our CI instance size.  I.E. it was due to test latency.
