### ISSUE TITLE
Intermittent Failure: Manage batches list batches

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#474]
Commit: 4b4ec7949770747d3e7915ee32c2c3335da849c3
Seed: 56148

NOTE: expected "Charlyn O'Conner" - actual "Charlyn O'conner " - i.e. uppercase C vs. lowercase c in last name.

Test ran successfully with seed 11645

```
  1) Manage batches list batches
     Failure/Error: expect(page).to have_content batch.creator
       expected to find text "Charlyn O'Conner" in "Skip to Content Search MIRA Go All View Charlyn O'conner profile Batches Show entries Search: ID Batch Type Creator Created at Items Status 1 Template Update person1_302@example.com less than a minute ago 1 Unavailable Showing 1 to 1 of 1 entries Previous1Next © 2017 Tufts University". (However, it was found 1 time using a case insensitive search.)
     # ./spec/features/batch_spec.rb:73:in `block (2 levels) in <top (required)>'
  2) Manage batches show batch
     Failure/Error: expect(page).to have_content batch.creator
       expected to find text "Charlyn O'Conner" in "Skip to Content Search MIRA Go All View Charlyn O'conner profile Batch Status All batches Batch Id 1 Type Template Update Record Count 1 Creator person1_304@example.com Created At 2017-10-20 01:47:08 UTC Status Unavailable Item ID Title Status Review Status 1831cj92z A Fistful of Tokyo City Unavailable © 2017 Tufts University". (However, it was found 1 time using a case insensitive search.)
     # ./spec/features/batch_spec.rb:79:in `block (2 levels) in <top (required)>'
Finished in 6 minutes 40 seconds (files took 19.96 seconds to load)
1364 examples, 2 failures, 31 pending
Failed examples:
rspec ./spec/features/batch_spec.rb:70 # Manage batches list batches
rspec ./spec/features/batch_spec.rb:76 # Manage batches show batch
Randomized with seed 56148
```

**Comment by mark-dce** [comment]
Due to a FFAKER inconsistency around names with apostrophes - closing as low-value work to fix

**Comment by mark-dce** [comment]
It looks like something in the Hyrax stack (possibly the presenter?) is mucking with display name.

Commit: 20a403439f24c8e4bef395711843bcb3494c4e2a
Seed: 27116

```
Failures:
  1) Manage batches list batches
     Failure/Error: expect(page).to have_content batch.creator
       expected to find text "Nevada McCullough" in "Skip to Content Search MIRA Go All View Nevada Mc Cullough profile Batches Show entries Search: ID Batch Type Creator Created at Items Status 1 Template Update person1_202@example.com less than a minute ago 1 Unavailable Showing 1 to 1 of 1 entries Previous1Next © 2017 Tufts University Version HEAD updated Not in deployed environment"
     # ./spec/features/batch_spec.rb:73:in `block (2 levels) in <top (required)>'
  2) Manage batches show batch
     Failure/Error: expect(page).to have_content batch.creator
       expected to find text "Nevada McCullough" in "Skip to Content Search MIRA Go All View Nevada Mc Cullough profile Batch Status All batches Batch Id 1 Type Template Update Record Count 1 Creator person1_204@example.com Created At 2017-12-08 18:14:58 UTC Status Unavailable Item ID Title Status Review Status t722h880z Electric Witch Unavailable © 2017 Tufts University Version HEAD updated Not in deployed environment"
     # ./spec/features/batch_spec.rb:79:in `block (2 levels) in <top (required)>'
Finished in 9 minutes 39 seconds (files took 18.57 seconds to load)
1400 examples, 2 failures, 17 pending
Failed examples:
rspec ./spec/features/batch_spec.rb:70 # Manage batches list batches
rspec ./spec/features/batch_spec.rb:76 # Manage batches show batch
Randomized with seed 27116
```

**Comment by mark-dce** [comment]
The issue with apostrophes is caused by this line:
https://github.com/samvera/hyrax/blob/4fd8d9ad3c32db7deffc3b5246af5d1459a4b046/app/models/concerns/hyrax/user.rb#L116

I'm not sure where the spaces are being removed.
