### ISSUE TITLE
Intermittent Failure: Create and revert a draft a logged in admin user should text "published"

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#475]
Commit: aaf728874672ca3898235951438cdfb36414be77
Seed: 10376

```
  1) Create and revert a draft a logged in admin user should text "published"
     Failure/Error: raise ActionController::RoutingError, "No route matches [#{env['REQUEST_METHOD']}] #{env['PATH_INFO'].inspect}"
     
     ActionController::RoutingError:
       No route matches [POST] "/concern/pdfs/5425k968s"
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:36:in `call_app'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:24:in `block in call'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/tagged_logging.rb:69:in `block in tagged'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/tagged_logging.rb:26:in `tagged'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/tagged_logging.rb:69:in `tagged'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:24:in `call'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/request_id.rb:24:in `call'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/static.rb:136:in `call'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/railties-5.0.4/lib/rails/engine.rb:522:in `call'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/capybara-2.14.4/lib/capybara/server.rb:44:in `call'
     # /home/travis/build/curationexperts/epigaea/vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
     # /home/travis/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
     # /home/travis/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
     # /home/travis/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
     # ------------------
     # --- Caused by: ---
     # Capybara::ElementNotFound:
     #   Unable to find link or button "Edit"
     #   ./spec/features/create_draft_spec.rb:40:in `block (3 levels) in <top (required)>'
Finished in 6 minutes 20 seconds (files took 19.57 seconds to load)
1364 examples, 1 failure, 31 pending
Failed examples:
rspec ./spec/features/create_draft_spec.rb:10 # Create and revert a draft a logged in admin user should text "published"
Randomized with seed 10376
```

**Comment by little9** [comment]
I've refactored this test quite a bit since this issue was made, if it pops up again re-open this issue
