### ISSUE TITLE
Intermittent CI Failure: metadata_export_spec / Roles is invalid

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#602]
Commit: 78603dee001b0d11001de516bcbb911769748c87
Seed: 10732

```
Failures:
  1) Export Metadata with logged in user export metadata for selected items
     Failure/Error: let(:user) { FactoryGirl.create(:admin) }
     
     ActiveRecord::RecordInvalid:
       Validation failed: Roles is invalid
     # ./spec/features/metadata_export_spec.rb:10:in `block (3 levels) in <top (required)>'
     # ./spec/features/metadata_export_spec.rb:15:in `block (3 levels) in <top (required)>'
  2) XmlImportPresenter#status when queued changes to queued
     Failure/Error:
       expect { import.batch.enqueue! }
         .to change { presenter.status }
         .to('Queued')
     
       expected `presenter.status` to have changed to "Queued", but did not change
     # ./spec/presenters/xml_import_presenter_spec.rb:68:in `block (4 levels) in <top (required)>'
Finished in 9 minutes 42 seconds (files took 23.36 seconds to load)
1380 examples, 2 failures, 28 pending
Failed examples:
rspec ./spec/features/metadata_export_spec.rb:18 # Export Metadata with logged in user export metadata for selected items
rspec ./spec/presenters/xml_import_presenter_spec.rb:67 # XmlImportPresenter#status when queued changes to queued
Randomized with seed 10732
```

**Comment by little9** [comment]
The second one is marked as optional in Travis now, so shouldn't come up again. I'm not sure if I've seen the first one before.
