### ISSUE TITLE
Intermittent CI Failure: batch publishing sends the user to the batch status page like on the catalog

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#667]
Commit: 11e35691394f36fd7328587b7467a56ca4e44038
Seed: 36593

```
Failures:

  1) batch publishing sends the user to the batch status page like on the catalog
     Failure/Error:
       within(:xpath, "//div[contains(@class, 'tufts-buttons')]") do
         click_on 'Publish'
       end
     
     Capybara::ElementNotFound:
       Unable to find xpath "//div[contains(@class, 'tufts-buttons')]"
     # ./spec/features/batch_edit_spec.rb:21:in `block (3 levels) in <top (required)>'

Finished in 9 minutes 40 seconds (files took 16.4 seconds to load)
1380 examples, 1 failure, 9 pending

Failed examples:

rspec ./spec/features/batch_edit_spec.rb:19 # batch publishing sends the user to the batch status page like on the catalog

Randomized with seed 36593
```

**Comment by mark-dce** [comment]
Commit: 24baa8cbf428ea879e16f28914a9a2837bdf8196
Seed: 38350

```
Failures:

  1) batch publishing sends the user to the batch status page like on the catalog
     Failure/Error: expect(page).to have_selector('.tufts-buttons')
       expected to find css ".tufts-buttons" but there were no matches. Also found "", which matched the selector but not all filters.
     # ./spec/features/batch_edit_spec.rb:26:in `block (3 levels) in <top (required)>'

Finished in 9 minutes 54 seconds (files took 10.85 seconds to load)
1393 examples, 1 failure, 9 pending

Failed examples:

rspec ./spec/features/batch_edit_spec.rb:24 # batch publishing sends the user to the batch status page like on the catalog

Randomized with seed 38350
```
