### ISSUE TITLE
Running single spec fails ???

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#692]
...but the same test passes in the full test suite.  Can anyone help me understand why this is happening?

```
$ git checkout master
Already on 'master'
Your branch is up-to-date with 'origin/master'.

$ git rev-parse HEAD
f5a786263c6254f986a5d375155318cdc45f35f6

$ bundle exec rake spec SPEC=app/views/_user_util_links.html.erb
/Users/mark/.rbenv/versions/2.3.4/bin/ruby -I/Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.6.0/lib:/Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-support-3.6.0/lib /Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.6.0/exe/rspec app/views/_user_util_links.html.erb

An error occurred while loading ./app/views/_user_util_links.html.erb.
Failure/Error: load file

SyntaxError:
  /Users/mark/_no_backup_/Projects/epigaea/app/views/_user_util_links.html.erb:1: syntax error, unexpected '<'
  <%= render '/controls' %>
   ^
  /Users/mark/_no_backup_/Projects/epigaea/app/views/_user_util_links.html.erb:3: syntax error, unexpected '<'
  <ul id="user_utility_links" class="nav navbar-nav navbar-right">
   ^
  /Users/mark/_no_backup_/Projects/epigaea/app/views/_user_util_links.html.erb:3: syntax error, unexpected keyword_class, expecting end-of-input
  <ul id="user_utility_links" class="nav navbar-nav navbar-right">
                                   ^
# /Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1922:in `load'
# /Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1922:in `load_spec_file_handling_errors'
# /Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1494:in `block in load_spec_files'
# /Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1492:in `each'
# /Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1492:in `load_spec_files'
# /Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:100:in `setup'
# /Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:86:in `run'
# /Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
# /Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:45:in `invoke'
# /Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.6.0/exe/rspec:4:in `<main>'
# 
#   Showing full backtrace because every line was filtered out.
#   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
#   RSpec::Configuration#backtrace_inclusion_patterns for more information.
No examples found.

Randomized with seed 13406


Finished in 0.00033 seconds (files took 0.20891 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Randomized with seed 13406

/Users/mark/.rbenv/versions/2.3.4/bin/ruby -I/Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.6.0/lib:/Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-support-3.6.0/lib /Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-core-3.6.0/exe/rspec app/views/_user_util_links.html.erb failed
```

**Comment by little9** [comment]
@mark-dce when I run single specs I need to make sure that I have `require 'rails_helper'` at the top or they won't run properly. If you aren't running them by themselves you don't need that.

**Comment by val99erie** [comment]
@mark-dce The problem is how you are calling your spec.  The file you passed in is not a spec file.
`$ bundle exec rake spec SPEC=app/views/_user_util_links.html.erb`

**Comment by val99erie** [comment]
oh i see.  you'll still get an error, even with a spec file.  ignore previous comment.

**Comment by no-reply** [comment]
> oh i see. you'll still get an error, even with a spec file. ignore previous comment.

Can you clarify? The steps to reproduce, and the error reported in this ticket seem to reflect ruby trying to parse an `.erb` as a spec.

**Comment by val99erie** [comment]
@no-reply Ah, sorry for confusing comment.  I think the problem is that the file being passed to `SPEC` is not a spec file.  I thought maybe rspec would be smart enough to find the corresponding spec for a source file, but that doesn't seem to be the case.  I suspect that Mark just needs to change his command to pass in a spec file instead of a source file.

**Comment by mark-dce** [comment]
Yup - that's all the problem is - I'm passing in the file that errored on me, not the spec that failed - totally my bad, but I was too close to it at the moment to see my obvious error.  Sorry to have bugged everyone :)
