### ISSUE TITLE
INTERMITTENT FAILURE: CI not finding fits.sh

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#850]
No idea what's causing this on a PR that changes one and only one markdown file (and only on the push build, the pr build runs fine).

https://github.com/curationexperts/epigaea/compare/b7e70d2d6017...199c775579bc

Commit: 199c775579bc2be4f71384cc82dd197bf720029e
Seed: 10763

```
Failures:
  1) submit a Fletcher School Capstone Project contribution 
     Failure/Error: actor.create_content(uploaded_file)
     
     RuntimeError:
       Unable to execute command "fits.sh -i "/home/travis/build/curationexperts/epigaea/tmp/uploads/hyrax/uploaded_file/file/1/hello.pdf""
       sh: 1: fits.sh: not found
     # ./app/jobs/attach_typed_files_to_work_job.rb:13:in `block in perform'
     # ./app/jobs/attach_typed_files_to_work_job.rb:10:in `each'
     # ./app/jobs/attach_typed_files_to_work_job.rb:10:in `perform'
     # ./app/actors/hyrax/actors/create_with_files_and_pass_types_actor.rb:18:in `attach_files'
     # ./app/actors/hyrax/actors/create_with_files_and_pass_types_actor.rb:10:in `create'
     # ./app/models/forms/contribution.rb:49:in `tufts_pdf'
     # ./app/models/forms/contribution.rb:70:in `save'
     # ./app/controllers/contribute_controller.rb:25:in `create'
     # ./spec/features/contribute/fletcher_school_capstone_spec.rb:22:in `block (2 levels) in <top (required)>'
  2) Batch#enqueue calls enqueue on batchable
     Failure/Error: raise("No Template found for #{name}.")
     
     RuntimeError:
       No Template found for Moomin Template.
     # ./app/lib/tufts/template.rb:49:in `for'
     # ./app/jobs/template_update_job.rb:12:in `perform'
     # ./app/models/template_update.rb:48:in `block in enqueue!'
     # ./app/models/template_update.rb:47:in `each'
     # ./app/models/template_update.rb:47:in `each_with_object'
     # ./app/models/template_update.rb:47:in `enqueue!'
     # ./app/models/batch.rb:29:in `enqueue!'
     # ./spec/models/batch_spec.rb:13:in `block (3 levels) in <top (required)>'
  3) Create a PDF  a new user contributes undergraduate research
     Failure/Error: actor.create_content(uploaded_file)
     
     RuntimeError:
       Unable to execute command "fits.sh -i "/home/travis/build/curationexperts/epigaea/tmp/uploads/hyrax/uploaded_file/file/1/pdf-sample.pdf""
       sh: 1: fits.sh: not found
     # ./app/jobs/attach_typed_files_to_work_job.rb:13:in `block in perform'
     # ./app/jobs/attach_typed_files_to_work_job.rb:10:in `each'
     # ./app/jobs/attach_typed_files_to_work_job.rb:10:in `perform'
     # ./app/actors/hyrax/actors/create_with_files_and_pass_types_actor.rb:18:in `attach_files'
     # ./app/actors/hyrax/actors/create_with_files_and_pass_types_actor.rb:10:in `create'
     # ./app/models/forms/generic_tisch_deposit.rb:28:in `tufts_pdf'
     # ./app/models/forms/contribution.rb:70:in `save'
     # ./app/controllers/contribute_controller.rb:25:in `create'
     # ------------------
     # --- Caused by: ---
     # Capybara::CapybaraError:
     #   Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
     #   ./spec/features/contribute/undergrad_scholarship_contribute_spec.rb:43:in `block (3 levels) in <top (required)>'
  4) submit an Undergraduate Honors Thesis contribution should text "Your deposit has been submitted for approval."
     Failure/Error: actor.create_content(uploaded_file)
     
     RuntimeError:
       Unable to execute command "fits.sh -i "/home/travis/build/curationexperts/epigaea/tmp/uploads/hyrax/uploaded_file/file/1/hello.pdf""
       sh: 1: fits.sh: not found
     # ./app/jobs/attach_typed_files_to_work_job.rb:13:in `block in perform'
     # ./app/jobs/attach_typed_files_to_work_job.rb:10:in `each'
     # ./app/jobs/attach_typed_files_to_work_job.rb:10:in `perform'
     # ./app/actors/hyrax/actors/create_with_files_and_pass_types_actor.rb:18:in `attach_files'
     # ./app/actors/hyrax/actors/create_with_files_and_pass_types_actor.rb:10:in `create'
     # ./app/models/forms/contribution.rb:49:in `tufts_pdf'
     # ./app/models/forms/contribution.rb:70:in `save'
     # ./app/controllers/contribute_controller.rb:25:in `create'
     # ------------------
     # --- Caused by: ---
     # Capybara::ExpectationNotMet:
     #   expected to find text "Your deposit has been submitted for approval." in "Internal Server Error Unable to execute command \"fits.sh -i \"/home/travis/build/curationexperts/epigaea/tmp/uploads/hyrax/uploaded_file/file/1/hello.pdf\"\" sh: 1: fits.sh: not found WEBrick/1.3.1 (Ruby/2.3.4/2017-03-30) at 127.0.0.1:34599"
     #   ./spec/features/contribute/undergrad_honors_thesis_spec.rb:36:in `block (2 levels) in <top (required)>'
Finished in 13 minutes 43 seconds (files took 22.9 seconds to load)
1549 examples, 4 failures, 11 pending
Failed examples:
rspec ./spec/features/contribute/fletcher_school_capstone_spec.rb:14 # submit a Fletcher School Capstone Project contribution 
rspec ./spec/models/batch_spec.rb:10 # Batch#enqueue calls enqueue on batchable
rspec ./spec/features/contribute/undergrad_scholarship_contribute_spec.rb:24 # Create a PDF  a new user contributes undergraduate research
rspec ./spec/features/contribute/undergrad_honors_thesis_spec.rb:18 # submit an Undergraduate Honors Thesis contribution should text "Your deposit has been submitted for approval."
Randomized with seed 10763
```

**Comment by bess** [comment]
I ran into this on a PR just now too. I'm going to try disabling CharacterizationJob. That's what we were doing on Laevigata to get around this issue and it worked well there.
