### ISSUE TITLE
HOUSEKEEPING: Intermittent CI Failure - Hyrax::Actors::HandleAssuranceActor#create when the next middleware fails does not equeue a job

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#864]
Commit: 18a47720984d8b915db9a50b4ee783ed8d31b91c
Seed: 49173

```
Failures:
  1) Hyrax::Actors::HandleAssuranceActor#create when the next middleware fails does not equeue a job
     Failure/Error: AdminSet.find_or_create_default_admin_set_id
     
     Ldp::Conflict:
       The repository type (http://fedora.info/definitions/v4/repository#Container) of this resource is system managed.
     # ./app/lib/tufts/workflow_setup.rb:19:in `set_default_workflow'
     # ./app/lib/tufts/workflow_setup.rb:10:in `setup'
     # ./app/lib/tufts/workflow_setup.rb:6:in `setup'
     # ./spec/rails_helper.rb:133:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # Ldp::NotFound:
     #   ./app/lib/tufts/workflow_setup.rb:19:in `set_default_workflow'
Finished in 12 minutes 45 seconds (files took 17.1 seconds to load)
1666 examples, 1 failure, 4 pending
Failed examples:
rspec ./spec/actors/hyrax/actors/handle_assurance_actor_spec.rb:62 # Hyrax::Actors::HandleAssuranceActor#create when the next middleware fails does not equeue a job
Randomized with seed 49173
```

**Comment by mark-dce** [comment]
Haven't seen this re-occur in more recent commits.
