### ISSUE TITLE
HOUSEKEEPING: Intermittent CI Failure - 

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#867]
Commit: 2b6fe9bc7a9685f69b80f8b0ded855179986222e
Seed: 21722

```
Failures:
  1) submit a Tish Library Reward contribution 
     Failure/Error: actor.create_content(uploaded_file)
     
     RuntimeError:
       Unable to execute command "fits.sh -i "/home/travis/build/curationexperts/epigaea/tmp/uploads/hyrax/uploaded_file/file/1/hello.pdf""
       sh: 1: fits.sh: not found
     # ./app/jobs/attach_typed_files_to_work_job.rb:13:in `block in perform'
     # ./app/jobs/attach_typed_files_to_work_job.rb:10:in `each'
     # ./app/jobs/attach_typed_files_to_work_job.rb:10:in `perform'
     # ./app/actors/hyrax/actors/create_with_files_and_pass_types_actor.rb:18:in `attach_files'
     # ./app/actors/hyrax/actors/create_with_files_and_pass_types_actor.rb:10:in `create'
     # ./app/models/forms/contribution.rb:49:in `tufts_pdf'
     # ./app/models/forms/contribution.rb:70:in `save'
     # ./app/controllers/contribute_controller.rb:25:in `create'
     # ./spec/features/contribute/tish_library_reward_spec.rb:22:in `block (2 levels) in <top (required)>'
  2) Create a Faculty Scholarship self contribution  a new user contributes faculty scholarship
     Failure/Error: actor.create_content(uploaded_file)
     
     RuntimeError:
       Unable to execute command "fits.sh -i "/home/travis/build/curationexperts/epigaea/tmp/uploads/hyrax/uploaded_file/file/2/pdf-sample.pdf""
       sh: 1: fits.sh: not found
     # ./app/jobs/attach_typed_files_to_work_job.rb:13:in `block in perform'
     # ./app/jobs/attach_typed_files_to_work_job.rb:10:in `each'
     # ./app/jobs/attach_typed_files_to_work_job.rb:10:in `perform'
     # ./app/actors/hyrax/actors/create_with_files_and_pass_types_actor.rb:18:in `attach_files'
     # ./app/actors/hyrax/actors/create_with_files_and_pass_types_actor.rb:10:in `create'
     # ./app/models/forms/contribution.rb:49:in `tufts_pdf'
     # ./app/models/forms/contribution.rb:70:in `save'
     # ./app/controllers/contribute_controller.rb:25:in `create'
     # ------------------
     # --- Caused by: ---
     # Capybara::CapybaraError:
     #   Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
     #   ./spec/features/contribute/faculty_scholarship_contribute_spec.rb:54:in `block (3 levels) in <top (required)>'
  3) Create a Faculty Scholarship self contribution  normalize spaces in entered fields
     Failure/Error: actor.create_content(uploaded_file)
     
     RuntimeError:
       Unable to execute command "fits.sh -i "/home/travis/build/curationexperts/epigaea/tmp/uploads/hyrax/uploaded_file/file/1/pdf-sample.pdf""
       sh: 1: fits.sh: not found
     # ./app/jobs/attach_typed_files_to_work_job.rb:13:in `block in perform'
     # ./app/jobs/attach_typed_files_to_work_job.rb:10:in `each'
     # ./app/jobs/attach_typed_files_to_work_job.rb:10:in `perform'
     # ./app/actors/hyrax/actors/create_with_files_and_pass_types_actor.rb:18:in `attach_files'
     # ./app/actors/hyrax/actors/create_with_files_and_pass_types_actor.rb:10:in `create'
     # ./app/models/forms/contribution.rb:49:in `tufts_pdf'
     # ./app/models/forms/contribution.rb:70:in `save'
     # ./app/controllers/contribute_controller.rb:25:in `create'
     # ------------------
     # --- Caused by: ---
     # Capybara::CapybaraError:
     #   Your application server raised an error - It has been raised in your test code because Capybara.raise_server_errors == true
     #   ./spec/rails_helper.rb:139:in `block (2 levels) in <top (required)>'
Finished in 16 minutes 59 seconds (files took 21.97 seconds to load)
1666 examples, 3 failures, 4 pending
Failed examples:
rspec ./spec/features/contribute/tish_library_reward_spec.rb:15 # submit a Tish Library Reward contribution 
rspec ./spec/features/contribute/faculty_scholarship_contribute_spec.rb:28 # Create a Faculty Scholarship self contribution  a new user contributes faculty scholarship
rspec ./spec/features/contribute/faculty_scholarship_contribute_spec.rb:65 # Create a Faculty Scholarship self contribution  normalize spaces in entered fields
Randomized with seed 21722
```

**Comment by no-reply** [comment]
[log.txt from the above build.](https://github.com/curationexperts/epigaea/files/1604356/log.txt)
