### ISSUE TITLE
HOUSEKEEPING: Intermittent Test Failure - XmlImport#enqueue! enqueues the correct job type

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#871]
Commit: 
Failing Seed: 15419
Passing Seed: 41915

```
Failures:

  1) XmlImport behaves like a batchable #enqueue! with ids in batch gives a hash associating ids to jobs
     Failure/Error:
       expect(batchable.enqueue!)
         .to include('123' => an_instance_of(String),
                     '124' => an_instance_of(String))
     
       expected {"124" => "1fe4299f-efcf-466e-aae9-ed70223733fc"} to include {"123" => (an instance of String)}
       Diff:
       @@ -1,3 +1,2 @@
       -"123" => (an instance of String),
       -"124" => (an instance of String),
       +"124" => "1fe4299f-efcf-466e-aae9-ed70223733fc",
       
     Shared Example Group: "a batchable" called from ./spec/models/xml_import_spec.rb:13
     # ./spec/support/shared_examples/batchable.rb:30:in `block (4 levels) in <top (required)>'

  2) XmlImport#enqueue! enqueues the correct job type
     Failure/Error:
       expect { import.enqueue! }
         .to enqueue_job(ImportJob)
         .with(import, [file], an_instance_of(String))
         .on_queue('batch')
         .once
     
       expected to enqueue exactly 1 jobs, with [#<XmlImport id: 11, metadata_file: "52ca6b73-391d-42ae-b3ab-4a19dae73684.xml", uploaded_file_ids: [27], created_at: "2018-01-05 04:14:45", updated_at: "2018-01-05 04:14:45", record_ids: {"2.pdf"=>"123"}>, [#<Hyrax::UploadedFile id: 27, file: "2.pdf", user_id: 44, file_set_uri: nil, created_at: "2018-01-05 04:14:44", updated_at: "2018-01-05 04:14:44">], #<RSpec::Matchers::AliasedMatcher:0x007ff875f7e778 @description_block=#<Proc:0x007ff87b1c65d0@/Users/mark/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rspec-expectations-3.6.0/lib/rspec/matchers/dsl.rb:31 (lambda)>, @base_matcher=#<RSpec::Matchers::BuiltIn::BeAnInstanceOf:0x007ff875f7e7a0 @expected=String, @matcher_name=:an_instance_of>>], on queue batch, but enqueued 0
     # ./spec/models/xml_import_spec.rb:123:in `block (3 levels) in <top (required)>'

Finished in 15 minutes 58 seconds (files took 11.04 seconds to load)
1666 examples, 2 failures

Failed examples:

rspec ./spec/models/xml_import_spec.rb[1:1:3:2:1] # XmlImport behaves like a batchable #enqueue! with ids in batch gives a hash associating ids to jobs
rspec ./spec/models/xml_import_spec.rb:122 # XmlImport#enqueue! enqueues the correct job type

Randomized with seed 15419
```

**Comment by mark-dce** [comment]
Note: tests only fail when running the full suite, not when running `./spec/models/xml_import_spec.rb` by itself with that seed.

**Comment by mark-dce** [comment]
We've not seen this error reoccur in CI builds for over two months, so I'm closing this ticket.

**Comment by mkorcy** [comment]
Got the same failure today.
```
Failures:

  1) XmlImport behaves like a batchable #enqueue! with ids in batch gives a hash associating ids to jobs
     Failure/Error: super
     
     ActiveRecord::RecordNotFound:
       Couldn't find Hyrax::PermissionTemplate
     Shared Example Group: "a batchable" called from ./spec/models/xml_import_spec.rb:13
     # /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/hyrax-2.0.0/app/actors/hyrax/actors/apply_permission_template_actor.rb:17:in `add_edit_users'
     # /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/hyrax-2.0.0/app/actors/hyrax/actors/apply_permission_template_actor.rb:9:in `create'
     # /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/hyrax-2.0.0/app/actors/hyrax/actors/default_admin_set_actor.rb:14:in `create'
     # /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/hyrax-2.0.0/app/actors/hyrax/actors/transfer_request_actor.rb:9:in `create'
     # /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/hyrax-2.0.0/app/actors/hyrax/actors/interpret_visibility_actor.rb:89:in `create'
     # /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/hyrax-2.0.0/app/actors/hyrax/actors/abstract_actor.rb:91:in `create'
     # /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/hyrax-2.0.0/app/actors/hyrax/actors/abstract_actor.rb:91:in `create'
     # /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/hyrax-2.0.0/app/actors/hyrax/actors/add_to_work_actor.rb:8:in `create'
     # /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/hyrax-2.0.0/app/actors/hyrax/actors/collections_membership_actor.rb:9:in `create'
     # /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/hyrax-2.0.0/app/actors/hyrax/actors/create_with_files_actor.rb:10:in `create'
     # ./app/actors/hyrax/actors/create_with_files_and_pass_types_actor.rb:10:in `create'
     # /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/hyrax-2.0.0/app/actors/hyrax/actors/create_with_remote_files_actor.rb:13:in `create'
     # /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/hyrax-2.0.0/app/actors/hyrax/actors/abstract_actor.rb:91:in `create'
     # /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/hyrax-2.0.0/app/actors/hyrax/actors/transactional_request.rb:11:in `block in create'
     # /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/hyrax-2.0.0/app/actors/hyrax/actors/transactional_request.rb:10:in `create'
     # ./app/services/tufts/import_service.rb:57:in `import_object!'
     # ./app/services/tufts/import_service.rb:29:in `import_object!'
     # ./app/jobs/import_job.rb:6:in `perform'
     # /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/i18n-0.9.0/lib/i18n.rb:265:in `with_locale'
     # ./app/models/xml_import.rb:65:in `block in enqueue!'
     # ./app/models/xml_import.rb:54:in `each'
     # ./app/models/xml_import.rb:54:in `each_with_object'
     # ./app/models/xml_import.rb:54:in `enqueue!'
     # ./spec/support/shared_examples/batchable.rb:30:in `block (4 levels) in <top (required)>'

Finished in 10 minutes 41 seconds (files took 9.12 seconds to load)
1668 examples, 1 failure

Failed examples:

rspec ./spec/models/xml_import_spec.rb[1:1:3:2:1] # XmlImport behaves like a batchable #enqueue! with ids in batch gives a hash associating ids to jobs

Randomized with seed 1213

[Coveralls] Outside the CI environment, not sending data.

mkorcy01@TTSESTSMK01: ~/Documents/workspace/2018/epigaea on master [?$]
$ rspec ./spec/models/xml_import_spec.rb
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's 'rails' settings.

Randomized with seed 25291
.........................

Finished in 27.69 seconds (files took 12.1 seconds to load)
25 examples, 0 failures

```

**Comment by mark-dce** [comment]
Just saw this again today

Commit: 7229588b6cafdbbe45312aa1f81925e7b1f55958
Seed: 8704
