### ISSUE TITLE
A copy of Tufts::Draftable has been removed from the module tree but is still active!

### ISSUE THREAD

**Issue by mkorcy** [curationexperts/epigaea#875]
I had a local copy of stock epigea sitting around unused for a few days (since Tuesday). When I went to deposit a single item through the dashboard today I got the error listed in the subject, full stacktrace below.  I tried to replicate this on the demo server but didn't see the same issue.  Not sure if this is related to running in Dev or has to do with the uptime of the app.  Have you seen this before?  

```
ArgumentError (A copy of Tufts::Draftable has been removed from the module tree but is still active!):
  
app/lib/tufts/draftable.rb:35:in `draft'
app/lib/tufts/draftable.rb:25:in `delete_draft'
app/controllers/tufts/publication_status_controller.rb:9:in `publish'
  Rendering /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/actionpack-5.0.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb
  Rendering /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/actionpack-5.0.4/lib/action_dispatch/middleware/templates/rescues/_source.text.erb
  Rendered /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/actionpack-5.0.4/lib/action_dispatch/middleware/templates/rescues/_source.text.erb (0.9ms)
  Rendering /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/actionpack-5.0.4/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb
  Rendered /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/actionpack-5.0.4/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.9ms)
  Rendering /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/actionpack-5.0.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb
  Rendered /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/actionpack-5.0.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (1.1ms)
  Rendered /Users/mkorcy01/.rvm/gems/ruby-2.3.4@epigea/gems/actionpack-5.0.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (78.1ms)
** [Honeybadger] Unable to send error report: API key is missing. id=862d03a5-fa8b-463d-95b6-88ec5fee6cf2 level=3 pid=73829
Started POST "/publication_statuses/2n49t1681/publish" for 127.0.0.1 at 2018-01-12 10:51:22 -0500
  User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2 ORDER BY `users`.`id` ASC LIMIT 1
  Role Exists (0.3ms)  SELECT  1 AS one FROM `roles` INNER JOIN `roles_users` ON `roles`.`id` = `roles_users`.`role_id` WHERE `roles_users`.`user_id` = 2 AND `roles`.`name` = 'admin' LIMIT 1
  Role Exists (0.2ms)  SELECT  1 AS one FROM `roles` INNER JOIN `roles_users` ON `roles`.`id` = `roles_users`.`role_id` WHERE `roles_users`.`user_id` = 2 AND `roles`.`name` = 'admin' LIMIT 1
Processing by Tufts::PublicationStatusController#publish as JS
  Parameters: {"id"=>"2n49t1681"}
  Load LDP (12.7ms) http://127.0.0.1:8984/rest/dev/2n/49/t1/68/2n49t1681 Service: 70287766996580
Completed 500 Internal Server Error in 35ms (ActiveRecord: 0.0ms)

```

**Comment by bess** [comment]
@mkorcy I have encountered that error before and it is specifically about how modules are loaded into memory in the development environment. Especially if your dev environment had been running for a few days, it's totally possible that some needed module got dropped from active memory. If you don't see it in production I think it's a phantom local environment memory thing.

**Comment by mark-dce** [comment]
Mike is seeing this issues at least daily, so we may want to dig into this a little more deeply.  Mike has experimented with eager loading without any success.

**Comment by mark-dce** [comment]
Problem disappears if Spring is disabled.  We believe this is a load / pre-load issue limited to the development environment.  Closing because it's probably not worth the effort for a deeper solution since dialing Spring seems to work.
